// <auto-generated />
using LePlug.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LePlug.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240821090505_addForeignKeyForCategoryProductRelationship")]
    partial class addForeignKeyForCategoryProductRelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LePlug.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Apparels"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Equipment"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Accessories"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Technology"
                        });
                });

            modelBuilder.Entity("LePlug.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Designed with a unique 8-panel swirl design, this ball offers superior visibility when in flight. This in turn improves accuracy during bumps, sets, and spikes. Composite leather cover provides low sting on wrists and arms and stands up to rough, routine play indoors. Nylon-wound center and composite bladder retain air and ball shape. Official size.",
                            ListPrice = 5999.0,
                            Manufacturer = "Mikasa Inc",
                            Price = 5799.0,
                            Price100 = 4999.0,
                            Price50 = 5299.0,
                            ProductName = "Mikasa MVA330 Composite Volleyball"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "The hoodie is made of thick cotton fabric which keeps in body heat so you can stay warm and comfortable.This drawstring double fabric hoodie with self-coloured",
                            ListPrice = 2500.0,
                            Manufacturer = "Urban Volleyball",
                            Price = 2299.0,
                            Price100 = 1999.0,
                            Price50 = 2199.0,
                            ProductName = "High Quality Hoodie"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "Explore our wide selection of men's volleyball shoes and sneakers! We carry the top-of-the-line brands like Nike, Mizuno, Adidas, and so much more",
                            ListPrice = 2500.0,
                            Manufacturer = "Asics",
                            Price = 2299.0,
                            Price100 = 1999.0,
                            Price50 = 2199.0,
                            ProductName = "Sport Shoes"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Keep your eyes on the net, not the floor. These adidas volleyball kneepads are made to fit the contours of your knee for a comfortable wear.",
                            ListPrice = 2500.0,
                            Manufacturer = "Addidas",
                            Price = 2299.0,
                            Price100 = 1999.0,
                            Price50 = 2199.0,
                            ProductName = "Knee Pads"
                        });
                });

            modelBuilder.Entity("LePlug.Models.Product", b =>
                {
                    b.HasOne("LePlug.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
